version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: c-mysql
    restart: always
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - ./mydata:/var/lib/mysql
  # phpmyadmin:
  #   image: phpmyadmin:latest
  #   container_name: c-phpmyadmin
  #   restart: always
  #   hostname: myadmin
  #   ports:
  #     - "8081:80"
  #   environment:
  #     - PMA_HOST=c-mysql

    